---
- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"

- include_tasks: debian.yml
  when: ansible_distribution == "debian"

- include_tasks: zsh.yml

- include_tasks: templates.yml